version: '2'
services:
 nginx:
   image: nginx
   ports:
    - "80:80"
    - "443:443"
   volumes:
    - ./volumes/nginx/conf.d:/etc/nginx/conf.d
    - /etc/letsencrypt:/etc/letsencrypt
   depends_on:
    - web
 web:
   build: ./web/
   ports:
    - "3000:3000"
   env_file:
    - .env
   depends_on:
    - db
 db:
   build: ./database/
   volumes:
    - ./volumes/mongo:/data/db
