version: '2'
services:
 web:
   build: ./web/
   ports:
    - "3000:3000"
   env_file:
    - .env
   depends_on:
    - db
 db:
   build: ./database/
   volumes:
    - ./volumes/mongo:/data/db
   environment:
    - MONGO_INITDB_DATABASE=ant
